### ISSUE TITLE
Not Showing In Steam

### ISSUE THREAD

**Issue by Vinshamr** [DFJacob/AbioticFactorDedicatedServer#7]
I have forwarded my ports but still don't see the server in-game. If I manually add the server to my favorites it will show an unnamed server in LAN but I can't connect. I see the following in my server console output, is this the problem?

Steam Dedicated Server API failed to initialize.
STEAM: [AppId: 2857200] Game Server API initialized 0
STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable.
STEAM: OnlineSubsystemSteam::Shutdown()
STEAM: Steam API failed to initialize!
STEAM: OnlineSubsystemSteam::Shutdown()

I tried running with the -NOSTEAM option as well and it didn't change anything.

**Comment by ValarianRossi** [comment]
I had a similar error message start showing up while I was troubleshooting a different problem. It happened after accidentally clicking one of the .exe files instead of the .bat file to start the server.

Apparently when I did so it started a server in the background without the .bat information and it would show up without a name on the LAN in game server browser. When I would try to start the server it would give me the error you mention above, though in my case I would still see a second server open on the LAN tab--though it was named a random string of numbers and apparently had no information from the .bat file.

**I fixed it by using Task Manager to find all the background processes associated with abiotic factor and ending them**.

**Comment by Vinshamr** [comment]
This got the error to go away but I still can't see my server in-game so I guess that wasn't the root cause.

**Comment by Vinshamr** [comment]
Not sure if this is just me grasping at straws but is there anything that needs to be done differently in Windows 11 from Windows 10 to get these servers past the firewall? I just went back and tried all my previous servers that I was running and I can't connect to any of them. The only thing that has happened to my PC since then was updating to 11.

**Comment by Stalig17** [comment]
Had the same issue, tripple checked i had the port forward correct, the runserver.bat querry port was correct. checked online to see if the that port was open for my IP and was not. just couldnt get it to open for some reason.

I fixed it by changing the RunServer.bat QueryPort= to 27016, then set the port forward on my router for 27016.  worked like a charm

**Comment by redredkrovy** [comment]
> Had the same issue, tripple checked i had the port forward correct, the runserver.bat querry port was correct. checked online to see if the that port was open for my IP and was not. just couldnt get it to open for some reason.
> 
> I fixed it by changing the RunServer.bat QueryPort= to 27016, then set the port forward on my router for 27016. worked like a charm

I'm running it in a LXC container on Proxmox with Ubuntu and had the same issue.  My server wasn't showing up but after I changed port 27015 to 27016 it started showing up on the list suddenly.  Don't know why that worked, I don't think I've got anything else running on port 27015 but I am hosting multiple game servers so maybe I overlooked something.
